### ISSUE TITLE
NVIDIA GeForce RTX 5060  - Blackwell architecture

### ISSUE THREAD

**Issue by reynunfra** [RosettaCommons/foundry#105]
First of all, thank you for developing and maintaining RFD3 and the foundry toolkit! This is an incredible resource for the protein design community :))

I'm encountering a CUDA compatibility error when trying to run RFD3 on my system with an NVIDIA GeForce RTX 5060 Laptop GPU (Blackwell architecture, compute capability sm_120).

_Error:_

_InstantiationException: Error in call to target 'rfd3.model.RFD3.RFD3':
AcceleratorError("CUDA error: no kernel image is available for execution on the device\nSearch for `cudaErrorNoKernelImageForDevice' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html
for more information.\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile
with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n")
full_key: model.net__

Is there a recommended PyTorch build or version that currently supports Blackwell (sm_120) architecture for use with RFD3?
Are there any workarounds besides waiting for PyTorch to add sm_120 support to their pre-built wheels?

I understand this is primarily a PyTorch limitation rather than an RFD3 issue, but any guidance from the team would be greatly appreciated! I'm happy to help test solutions if needed :)
Thank you again for your work on this project!

**Comment by rclune** [comment]
From what I understand, it's likely that you will need to wait until PyTorch supports sm_120, however a similar issue was made for RFdiffusion not too long ago. You might be able to find a work around based on the image they made? 
Here's the relevant issue: https://github.com/RosettaCommons/RFdiffusion/issues/380

**Comment by Young-Roseta** [comment]
It seems that we met the same problems:
InstantiationException: Error in call to target 'rfd3.model.RFD3.RFD3':
RuntimeError('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n')
full_key: model.net

**Comment by lg1243610235-cmyk** [comment]
please run "pip install torch==2.9.1+cu128 torchvision==0.24.1+cu128 torchaudio==2.9.1+cu128 --extra-index-url https://download.pytorch.org/whl/cu128" after install foundry.
The answer is from issues#70 by "Wenzhao-protein"

**Comment by Forever8341** [comment]
update pytorch. It supports Blackwell architecture now. My GPU is RTX pro 6000 and works fine with it now

**Comment by reynunfra** [comment]
Thank you all for the suggestions and help! :)
I can confirm that updating PyTorch fixed the issue - RFD3 now runs correctly on RTX 5060 (Blackwell, sm_120).
Thanks again for the heads-up about the update!

**Comment by rclune** [comment]
Closing because it seems like a solution has been found!
