### ISSUE TITLE
RTX5080 can not run RFD3

### ISSUE THREAD

**Issue by LeePan2003** [RosettaCommons/foundry#70]
erro：
InstantiationException: Error in call to target 'rfd3.model.RFD3.RFD3':
RuntimeError('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might
be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor
debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side
assertions.\n')
full_key: model.net

**Comment by Sahalona** [comment]
I ran into the same issue as you. After sending the error message to an AI, it suggested that it might be due to version incompatibility between PyTorch and CUDA. Once I removed the original installation and reinstalled a compatible version, I got it working.

**Comment by Wenzhao-protein** [comment]
I had the same problem and resolved it by updating my PyTorch version. Here is the .yml file I used in case it’s helpful.

[rc_foundry_rtx5090.yml](https://github.com/user-attachments/files/24015788/rc_foundry_rtx5090.yml)

**Comment by LeePan2003** [comment]
Thanks, Fixed it
